# These are supported funding model platforms

github: [guanwei1117-ctrl]
# patreon: # 暂未开通
# open_collective: # 暂未开通
# ko_fi: # 暂未开通
# tidelift: # 暂未开通
# community_bridge: # 暂未开通
# liberapay: # 暂未开通
# issuehunt: # 暂未开通
# otechie: # 暂未开通
# custom: ['https://www.guanwei-stylemate.com']